[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix ../frontend",
  "npm run build --prefix ../frontend",
  "pip install -r requirements.txt"
]

[start]
cmd = "bash start.sh"

